# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoVersionCheckHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('excel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mtime', models.DateTimeField(blank=True, null=True)),
                ('check_count', models.IntegerField(blank=True, null=True)),
                ('file_exists_status', models.IntegerField(blank=True, null=True)),
                ('tar_status', models.IntegerField(blank=True, null=True)),
                ('excel_datas', models.TextField(blank=True, null=True)),
                ('is_del', models.IntegerField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wo_version_check_history',
                'managed': False,
            },
        ),
    ]
