# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-17 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WoJenkinsServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('locate_service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_app_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_bin', models.IntegerField(blank=True, null=True)),
                ('is_config', models.IntegerField(blank=True, null=True)),
                ('sup_group', models.CharField(blank=True, max_length=255, null=True)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('service_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('ctime', models.DateTimeField(blank=True, null=True)),
                ('mtime', models.DateTimeField(blank=True, null=True)),
                ('is_del', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wo_jenkins_services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WoSupervisorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_del', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wo_supervisor_group',
                'managed': False,
            },
        ),
    ]
